version: '3.3'

services:  
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgressql/data

  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    command: sh

  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    depends_on:
      - pg
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST

  lb:
    image: zerxan/lb:latest
    environment:
      - PROXY_UPSTREAM
    depends_on:
      - webapp
    ports:
      - 80:80


volumes:
  pg-data: