version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
  
  pg:
    image: postgres:9.6-alpine
    env_file:
      - ./db.env
    volumes:
      - pg-data:/var/lib/postgressql/data

  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    command: sh

volumes:
  pg-data: