version: '3.3'

services:
  nodewebapp:
    image: zerxan/nodewebapp:v1
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

  lb:
    image: zerxan/lb:latest
    environment:
      - PROXY_UPSTREAM="nodewebapp:3000"
    depends_on:
      - nodewebapp
    ports:
      - 80:80